FROM node:20-alpine

WORKDIR /app

COPY package.json yarn.lock* ./
RUN yarn install

COPY . .

EXPOSE 3000

ENV NEXT_TELEMETRY_DISABLED=1
ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true

CMD ["yarn", "dev", "-H", "0.0.0.0", "-p", "3000"]
